plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-image-size
  

# SEO Stuff
author: joelchrono12
description: My personal blog, where I share my interests and hobbies
lang: en
locale: en_US
url: "https://joelchrono12.netlify.app"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 30
